/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AlexAuthor__factory } from "./AlexAuthor__factory";
export { AlexLearner__factory } from "./AlexLearner__factory";
